name: GitHub Release

on:
  push:
    tags:
      - "vibe-llama-core@v[0-9].[0-9]+.[0-9]+*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build
        working-directory: packages/vibe-llama-core/
        run: uv build -o dist

      - name: Publish to PyPI
        working-directory: packages/vibe-llama-core/
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "packages/vibe-llama-core/dist/*"
          generateReleaseNotes: true
